<?php

namespace Modules\Region\Entities;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

class Region extends Model
{

    use NodeTrait;
    protected $primaryKey = 'id';

    protected $table = 'region';

    protected $fillable = ['title'];


//    protected static function boot()
//    {
//        parent::boot(); // TODO: Change the autogenerated stub
//
//        static::created(function ($model) {
//            \Cache::tags(config('app.name'))->flush();
//        });
//
//        static::updated(function ($model) {
//            \Cache::tags(config('app.name'))->flush();
//        });
//
//        static::deleted(function ($model) {
//            \Cache::tags(config('app.name'))->flush();
//        });
//
//    }
}
