<?php

namespace Modules\Setting\Entities;

use Illuminate\Database\Eloquent\Model;

class Domain extends Model
{
    protected $primaryKey = 'key';

    protected $table = 'domain';

    public $incrementing = false;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            \Cache::flush();
        });

        static::updated(function ($model) {
            \Cache::flush();
        });

        static::deleted(function ($model) {
            \Cache::flush();
        });

    }

    public function links()
    {
        return $this->belongsToMany(Link::class, 'domain_has_links')->withPivot(['value']);
    }

    public function sticky()
    {
        return $this->hasOne(StickyConfig::class, 'domain_key');
    }


    public function app()
    {
        return $this->belongsToMany(Link::class, 'domain_has_links')->where('type', '=', 'app')->withPivot(['value']);
    }

    public function license()
    {
        return $this->belongsToMany(Link::class, 'domain_has_links')->where('type', '=', 'license')->withPivot(['value']);
    }


    public function socialMedia()
    {
        return $this->belongsToMany(Link::class, 'domain_has_links')->where('type', '=', 'social')->withPivot(['value']);
    }


    public function communicationChannels()
    {
        return $this->belongsToMany(Link::class, 'domain_has_links')->where('type', '=','contact')->withPivot(['value']);
    }

}
