<?php

namespace Modules\Tag\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Blog\Entities\Content;

class Tag extends Model
{
    protected $table = 'tag';

    protected $primaryKey = 'id';

    protected $guarded = [];

    public $timestamps= false;

    protected $hidden = ['pivot'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            \Cache::flush();
        });

        static::updated(function ($model) {
            \Cache::flush();
        });

        static::deleted(function ($model) {
            \Cache::flush();
        });

    }

    public function contents()
    {
        return $this->belongsToMany(Content::class, 'content_has_tags', 'tag_id', 'content_id');
    }

}
