<?php

namespace Developer\Payment\Gateway\Zarinpal;


use Developer\Payment\GatewayAbstract;
use Developer\Payment\GatewayInterface;
use Illuminate\Support\Facades\Log;

use SoapClient;

class Zarinpal extends GatewayAbstract implements GatewayInterface
{

    private $MerchantCode;


    public function __construct()
    {
        $this->MerchantCode = env('ZARINPAL_MERCHANT_ID');
        $this->gateway = 'zarinpal';
    }

    public function setAmount($amount)
    {
        $this->amount = $amount;
    }

    public function setCallback($url)
    {
        $this->callback = $url;
    }

    public function setDescription($description)
    {
        $this->description = $description;
    }

    public function ready()
    {
        return parent::ready(); // TODO: Change the autogenerated stub
    }



    public function setRefId($refId)
    {
        $this->refId = $refId;
    }

    /**
     *
     *
     */
    public function redirect()
    {
        $url = "https://www.zarinpal.com/pg/services/WebGate/wsdl";

        $data = [
            'Amount' => $this->amount,
            'MerchantID' => $this->MerchantCode,
            'CallbackURL' => $this->callback,
            'Description' => $this->description,
        ];

        $client = new SoapClient($url, ['encoding' => 'UTF-8']);

        $result = $client->PaymentRequest($data);

        if ($result->Status == 100) {

            return response([
                'status' => true,
                'msg' => 'در حال اتصال به درگاه بانک',
                'payload' => [
                    'action' => 'https://www.zarinpal.com/pg/StartPay/' . $result->Authority,
                    'method' => 'GET',
                    'fields' => []
                ]
            ]);

        }

        switch ($result->Status) {
            case "-1":
                $msg =  'اطلاعات ارسال شده ناقص است';
                break;
            case "-2":
                $msg =  'IP و يا مرچنت كد پذيرنده صحيح نيست';
                break;
            case "-3":
                $msg =  'با توجه به محدوديت هاي شاپرك امكان پرداخت با رقم درخواست شده ميسر نمي باشد';
                break;
            case "-4":
                $msg =  'سطح تاييد پذيرنده پايين تر از سطح نقره اي است';
                break;
            case "-11":
                $msg =  'درخواست مورد نظر يافت نشد';
                break;
            case "-12":
                $msg =  'امكان ويرايش درخواست ميسر نمي باشد';
                break;
            case "-21":
                $msg =  'هيچ نوع عمليات مالي براي اين تراكنش يافت نشد';
                break;
            case "-22":
                $msg =  'تراكنش نا موفق مي باشد';
                break;
            case "-33":
                $msg =  'رقم تراكنش با رقم پرداخت شده مطابقت ندارد';
                break;
            case "-34":
                $msg =  'سقف تقسيم تراكنش از لحاظ تعداد يا رقم عبور نموده است';
                break;
            case "-40":
                $msg =  'اجازه دسترسي به متد مربوطه وجود ندارد';
                break;
            case "-41":
                $msg =  'اطلاعات ارسال شده مربوط به AdditionalData غيرمعتبر مي باشد .';
                break;
            case "-42":
                $msg =  'مدت زمان معتبر طول عمر  شناسه  پرداخت بايد بين 30دقيه تا 45روز مي باش';
                break;
            case "-54":
                $msg =  'درخواست مورد نظر آرشيو شده است .';
                break;
            case "101":
                $msg =  'عمليات پرداخت موفق بوده وقبلا PaymentVerification تراكنش انجام شده است';
                break;
            case "100":
                $msg =  'عملیات با موفقیت انجام شد';
                break;
        }

        return response(['status' => false, 'msg' => $msg]);
    }


    public function verify($transaction)
    {
        $url = "https://www.zarinpal.com/pg/services/WebGate/wsdl";

        $parameter = [
            'MerchantID' => $this->MerchantCode,
            'Authority' => $this->refId,
            'Amount' => $this->amount,
        ];

        $client = new SoapClient($url, ['encoding' => 'UTF-8']);

        $result = $client->PaymentVerification($parameter);

        if ($result->Status == 100) {

            $this->refId = $result->RefID;
            $this->transactionSucceed($transaction);
            return ['status' => true, 'payload' => $result];
        }

        switch ($result->Status) {
            case "-1":
                $msg =  'اطلاعات ارسال شده ناقص است';
                break;
            case "-2":
                $msg =  'IP و يا مرچنت كد پذيرنده صحيح نيست';
                break;
            case "-3":
                $msg =  'با توجه به محدوديت هاي شاپرك امكان پرداخت با رقم درخواست شده ميسر نمي باشد';
                break;
            case "-4":
                $msg =  'سطح تاييد پذيرنده پايين تر از سطح نقره اي است';
                break;
            case "-11":
                $msg =  'درخواست مورد نظر يافت نشد';
                break;
            case "-12":
                $msg =  'امكان ويرايش درخواست ميسر نمي باشد';
                break;
            case "-21":
                $msg =  'هيچ نوع عمليات مالي براي اين تراكنش يافت نشد';
                break;
            case "-22":
                $msg =  'تراكنش نا موفق مي باشد';
                break;
            case "-33":
                $msg =  'رقم تراكنش با رقم پرداخت شده مطابقت ندارد';
                break;
            case "-34":
                $msg =  'سقف تقسيم تراكنش از لحاظ تعداد يا رقم عبور نموده است';
                break;
            case "-40":
                $msg =  'اجازه دسترسي به متد مربوطه وجود ندارد';
                break;
            case "-41":
                $msg =  'اطلاعات ارسال شده مربوط به AdditionalData غيرمعتبر مي باشد .';
                break;
            case "-42":
                $msg =  'مدت زمان معتبر طول عمر  شناسه  پرداخت بايد بين 30دقيه تا 45روز مي باش';
                break;
            case "-54":
                $msg =  'درخواست مورد نظر آرشيو شده است .';
                break;
            case "101":
                $msg =  'عمليات پرداخت موفق بوده وقبلا PaymentVerification تراكنش انجام شده است';
                break;
            case "100":
                $msg =  'عملیات با موفقیت انجام شد';
                break;
        }

        $this->transactionFailed($transaction);

        return ['status' => false, 'msg' => $msg];
    }

}
