<?php

namespace Modules\Blog\Entities;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;
use Modules\Upload\Entities\File;

class Category extends Model
{
    use NodeTrait;

    protected $primaryKey = 'id';

    protected $table = 'content_category';

    protected $guarded = [];

    public $timestamps = false;

    protected $hidden = ['pivot'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            \Cache::flush();
        });

        static::updated(function ($model) {
            \Cache::flush();
        });

        static::deleted(function ($model) {
            \Cache::flush();
        });

    }

    public function files()
    {
        return $this->morphMany(\Modules\FileManager\Entities\File::class, 'fileable');
    }


    public function contents()
    {
        return $this->belongsToMany(Content::class, 'content_has_categories', 'category_id', 'content_id');
    }

}
