<?php

namespace Modules\Blog\Entities;

use Illuminate\Database\Eloquent\Model;
use Modules\Product\Entities\Product;
use Modules\Tag\Entities\Tag;
use Modules\User\Entities\User;

class Content extends Model
{

    protected $table = 'content';

    protected $primaryKey = 'id';

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            \Cache::flush();
        });

        static::updated(function ($model) {
            \Cache::flush();
        });

        static::deleted(function ($model) {
            \Cache::flush();
        });

    }

    public function createdBy()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function files()
    {
        return $this->morphMany(\Modules\FileManager\Entities\File::class, 'fileable');
    }


    public function categories()
    {
        return $this->belongsToMany(Category::class, 'content_has_categories', 'content_id', 'category_id');
    }


    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'content_has_tags', 'content_id', 'tag_id');
    }

    public function products()
    {
        return $this->belongsToMany(Product::class, 'content_has_products', 'content_id', 'product_id');
    }

}
