<?php

namespace Modules\Product\Entities;

use Illuminate\Database\Eloquent\Model;

class PackageType extends Model
{
    const IS_BULK = 0;
    const IS_COUNTABLE = 1;


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            \Cache::flush();
        });

        static::updated(function ($model) {
            \Cache::flush();
        });

        static::deleted(function ($model) {
            \Cache::flush();
        });

    }


    protected $primaryKey = 'id';

    protected $table = 'package_type';

    protected $guarded = [];
}
