<?php

namespace Modules\Product\Entities;

use Illuminate\Database\Eloquent\Model;

class Pins extends Model
{
    protected $table = 'product_pins';

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            \Cache::flush();
        });

        static::updated(function ($model) {
            \Cache::flush();
        });

        static::deleted(function ($model) {
            \Cache::flush();
        });

    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }

    public function priceParameters()
    {
        return $this->belongsToMany(PriceParameter::class, 'product_pins_has_price_parameter', 'product_pins_id', 'price_parameter_id');
    }
}
