// auth login
export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_REFRESH = 'AUTH_REFRESH';
export const AUTH_DIALOG = 'AUTH_DIALOG';

// setting
export const SETTING_REQUESTING = 'SETTING_REQUESTING';
export const SETTING_SUCCESS = 'SETTING_SUCCESS';
export const SETTING_FAILURE = 'SETTING_FAILURE';

export const BLOG_REQUESTING = 'BLOG_REQUESTING';
export const BLOG_SUCCESS = 'BLOG_SUCCESS';
export const BLOG_FAILURE = 'BLOG_FAILURE';



export const PRODUCT_SWIPER_REQUESTING = 'PRODUCT_SWIPER_REQUESTING';
export const PRODUCT_SWIPER_SUCCESS = 'PRODUCT_SWIPER_SUCCESS';
export const PRODUCT_SWIPER_FAILURE = 'PRODUCT_SWIPER_FAILURE';

export const BRAND_REQUESTING = 'BRAND_REQUESTING';
export const BRAND_SUCCESS = 'BRAND_SUCCESS';
export const BRAND_FAILURE = 'BRAND_FAILURE';

export const SLIDER_REQUESTING = 'SLIDER_REQUESTING';
export const SLIDER_SUCCESS = 'SLIDER_SUCCESS';
export const SLIDER_FAILURE = 'SLIDER_FAILURE';
